[build]
  command = "expo export --platform web"
  publish = "dist"

[dev]
  command = "npm run start"

[functions]
  # Tell Netlify where your serverless functions live
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
